version: "3.8"
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-shared
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # MYSQL_DATABASE: user_center
    volumes:
      - ./mysql-data:/var/lib/mysql
    user: mysql:mysql

  # 后端服务
  uc-backend:
    build: ./user-center-backend
    container_name: uc-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # 这里连接的是上面的 mysql-db
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/user_center?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_USERNAME: root
    depends_on:
      - mysql-db
